package com.base.iso.util.log;

import java.util.Iterator;
import java.util.Vector;
import java.util.concurrent.ConcurrentHashMap;

import com.base.iso.interfaces.iDestroyable;
import com.base.iso.interfaces.log.iLogListener;
import com.base.iso.interfaces.log.iLogProducer;
import com.base.iso.interfaces.log.iLogSource;
import com.base.iso.interfaces.log.iLoggeable;

/**
 * Peer class Logger forwards LogEvents generated by LogSources 
 * to LogListeners.
 * Logger subsystem. 
 * @see LogEvent
 * @see iLogSource
 * @see iLogListener
 * @see iLoggeable
 * @see SimpleLogListener
 * @see RotateLogListener
 */
@SuppressWarnings("unchecked")
public class Logger implements iLogProducer {
    
    String name;
    Vector listeners;
    static boolean versionShown = false;
    private static final ConcurrentHashMap<String, Logger> loggers = new ConcurrentHashMap<>();

    public Logger () {
        super();
        listeners = new Vector ();
        name = "";
    }
    public void addListener (iLogListener l) {
        synchronized (listeners) {
            listeners.add (l);
        }
    }
    public void removeListener (iLogListener l) {
        synchronized (listeners) {
            listeners.remove (l);
        }
    }
    public void removeAllListeners () {
        synchronized (listeners) {
            Iterator i = listeners.iterator();
            while (i.hasNext()) {
                iLogListener l = ((iLogListener) i.next());
                if (l instanceof iDestroyable) {
                    ((iDestroyable) l).destroy ();
                }
            }
            listeners.clear ();
        }
    }
    public static void log (LogEvent evt) {
        Logger l = null;
        iLogSource source = evt.getSource();
        if (!versionShown) {
            evt.addMessage ("");
            // evt.addMessage (Q2.getVersionString());
            versionShown = !versionShown;
        }
        if (source != null)
            l = source.getLogger();
        if (l != null && l.hasListeners ()) {
            synchronized (l.listeners) {
                Iterator i = l.listeners.iterator();
                while (i.hasNext() && evt != null) 
                    evt = ((iLogListener) i.next()).log (evt);
            }
        }
    }
    /**
     * associates this Logger with a name using NameRegistrar
     * @param name name to register
     * @see NameRegistrar
     */
    public void setName (String name) {
        this.name = name;
        loggers.putIfAbsent("logger."+name, this);  // register in map
    }
    /**
     * destroy logger
     */
    public void destroy () {
        loggers.remove("logger."+name);  // remove from a map
        removeAllListeners ();
    }
    /**
     * @return logger instance with given name. Creates one if necessary
     * @see NameRegistrar
     */
    public synchronized static Logger getLogger (String name) {
   
        return loggers.computeIfAbsent(name, key -> {
            Logger l = new Logger();
            l.setName(key);
            return l;
        });
    }
    /**
     * @return this logger's name ("" if no name was set)
     */
    public String getName() {
        return this.name;
    }
    /**
     * Used by heavy used methods to avoid LogEvent creation 
     * @return true if Logger has associated LogListsners
     */
    public boolean hasListeners() {
        synchronized (listeners) {
            return listeners.size() > 0;
        }
    }
}
